# Generated by Django 4.1.13 on 2026-02-10 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "performed_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=120)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                (
                    "calories_burned",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="workouts.workout",
                    ),
                ),
            ],
        ),
    ]
