# Generated by Django 4.2 on 2026-02-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exerciseentry",
            name="auto_classified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="exerciseentry",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="exerciseentry",
            name="muscle_group",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
