# Generated by Django 4.2 on 2026-02-24

from django.db import migrations


def seed_library(apps, schema_editor):
    ExerciseLibrary = apps.get_model("workouts", "ExerciseLibrary")
    seeds = [
        {
            "name": "Brisk Walking",
            "category": "cardio",
            "muscle_group": "legs",
            "description": "Low-impact cardio to improve endurance and recovery.",
            "instructions": "Walk at a pace where talking is possible but slightly challenging for 20-45 minutes.",
        },
        {
            "name": "Jogging",
            "category": "cardio",
            "muscle_group": "legs",
            "description": "Steady-state cardio for aerobic capacity.",
            "instructions": "Jog at conversational pace. Keep shoulders relaxed and cadence consistent.",
        },
        {
            "name": "Cycling",
            "category": "cardio",
            "muscle_group": "legs",
            "description": "Joint-friendly cardio with easy intensity scaling.",
            "instructions": "Maintain smooth cadence and moderate resistance for 20-60 minutes.",
        },
        {
            "name": "Jump Rope",
            "category": "hiit",
            "muscle_group": "full body",
            "description": "High-efficiency conditioning and coordination drill.",
            "instructions": "Perform 30-60 second rounds with short rests. Land softly on the balls of your feet.",
        },
        {
            "name": "Push-Up",
            "category": "strength",
            "muscle_group": "chest",
            "description": "Upper-body compound movement for chest, shoulders, and triceps.",
            "instructions": "Keep body in a straight line, lower chest under control, then press up.",
        },
        {
            "name": "Bench Press",
            "category": "strength",
            "muscle_group": "chest",
            "description": "Primary horizontal pushing strength exercise.",
            "instructions": "Set shoulder blades, lower bar to mid-chest, press with controlled tempo.",
        },
        {
            "name": "Squat",
            "category": "strength",
            "muscle_group": "legs",
            "description": "Foundational lower-body compound movement.",
            "instructions": "Brace core, sit down and back, keep knees tracking over toes, stand up strongly.",
        },
        {
            "name": "Deadlift",
            "category": "strength",
            "muscle_group": "back",
            "description": "Posterior-chain compound lift for strength and power.",
            "instructions": "Hinge at hips, keep neutral spine, drive through feet, and stand tall.",
        },
        {
            "name": "Lunge",
            "category": "strength",
            "muscle_group": "legs",
            "description": "Unilateral lower-body movement for balance and strength.",
            "instructions": "Step forward, lower both knees to comfortable depth, push back to start.",
        },
        {
            "name": "Plank",
            "category": "core",
            "muscle_group": "core",
            "description": "Isometric core stability exercise.",
            "instructions": "Keep hips level and ribs down. Hold 20-90 seconds with steady breathing.",
        },
        {
            "name": "Row",
            "category": "strength",
            "muscle_group": "back",
            "description": "Upper-back pulling exercise to improve posture and strength.",
            "instructions": "Pull elbows toward hips, pause briefly, and lower under control.",
        },
        {
            "name": "Mountain Climbers",
            "category": "hiit",
            "muscle_group": "core",
            "description": "Bodyweight conditioning drill with core demand.",
            "instructions": "Start in plank, drive knees alternately with stable shoulders and hips.",
        },
    ]
    for item in seeds:
        ExerciseLibrary.objects.get_or_create(name=item["name"], defaults=item)


def unseed_library(apps, schema_editor):
    ExerciseLibrary = apps.get_model("workouts", "ExerciseLibrary")
    names = [
        "Brisk Walking",
        "Jogging",
        "Cycling",
        "Jump Rope",
        "Push-Up",
        "Bench Press",
        "Squat",
        "Deadlift",
        "Lunge",
        "Plank",
        "Row",
        "Mountain Climbers",
    ]
    ExerciseLibrary.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0005_exerciselibrary_workoutplan"),
    ]

    operations = [
        migrations.RunPython(seed_library, unseed_library),
    ]
