# Generated by Codex on 2026-04-28

from django.db import migrations


EXERCISE_LIBRARY_SEEDS = [
    {
        "name": "Trail Run",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Outdoor running over mixed terrain.",
        "instructions": "Keep a steady pace, shorten stride on climbs, and stay light on uneven ground.",
    },
    {
        "name": "Sprint Intervals",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Short high-intensity running intervals for speed and conditioning.",
        "instructions": "Alternate hard sprints with full walking recovery. Warm up before starting.",
    },
    {
        "name": "Stationary Bike",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Indoor cycling for low-impact conditioning.",
        "instructions": "Set seat height comfortably and maintain smooth cadence with moderate resistance.",
    },
    {
        "name": "Rowing Machine",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Full-body cardio using an indoor rower.",
        "instructions": "Drive with legs first, then lean back slightly and pull handle to lower ribs.",
    },
    {
        "name": "Elliptical",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Low-impact machine cardio.",
        "instructions": "Stand tall, keep feet flat, and use handles for balanced upper-body rhythm.",
    },
    {
        "name": "Stair Climber",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Machine-based climbing cardio.",
        "instructions": "Use light hand support, step through the full foot, and avoid leaning heavily on rails.",
    },
    {
        "name": "Swimming",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Low-impact full-body cardio in the pool.",
        "instructions": "Swim continuous laps or intervals while keeping relaxed breathing and steady form.",
    },
    {
        "name": "Hiking",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Outdoor endurance walking over varied terrain.",
        "instructions": "Use a sustainable pace and keep posture tall on climbs and descents.",
    },
    {
        "name": "Incline Dumbbell Press",
        "category": "strength",
        "muscle_group": "chest",
        "description": "Incline pressing movement for upper chest and shoulders.",
        "instructions": "Set bench to a moderate incline, lower dumbbells under control, and press evenly.",
    },
    {
        "name": "Dumbbell Chest Fly",
        "category": "strength",
        "muscle_group": "chest",
        "description": "Chest isolation movement with dumbbells.",
        "instructions": "Use a slight elbow bend, open arms under control, and bring dumbbells together above chest.",
    },
    {
        "name": "Overhead Press",
        "category": "strength",
        "muscle_group": "shoulders",
        "description": "Vertical pressing movement for shoulders and triceps.",
        "instructions": "Brace core, press overhead in a straight path, and avoid overextending the lower back.",
    },
    {
        "name": "Dumbbell Shoulder Press",
        "category": "strength",
        "muscle_group": "shoulders",
        "description": "Seated or standing dumbbell press for shoulders.",
        "instructions": "Start at shoulder height, press overhead evenly, and lower with control.",
    },
    {
        "name": "Lateral Raise",
        "category": "strength",
        "muscle_group": "shoulders",
        "description": "Shoulder isolation movement for side delts.",
        "instructions": "Raise weights to shoulder height with soft elbows and controlled tempo.",
    },
    {
        "name": "Face Pulls",
        "category": "strength",
        "muscle_group": "shoulders",
        "description": "Rear-delt and upper-back cable movement.",
        "instructions": "Pull rope toward face with elbows high and squeeze shoulder blades together.",
    },
    {
        "name": "Tricep Dips",
        "category": "strength",
        "muscle_group": "arms",
        "description": "Bodyweight triceps and chest movement.",
        "instructions": "Lower under control with shoulders stable, then press back to lockout.",
    },
    {
        "name": "Tricep Pushdown",
        "category": "strength",
        "muscle_group": "arms",
        "description": "Cable isolation exercise for triceps.",
        "instructions": "Keep elbows pinned near ribs and extend arms without swinging.",
    },
    {
        "name": "Pull Up",
        "category": "strength",
        "muscle_group": "back",
        "description": "Bodyweight vertical pull for back and arms.",
        "instructions": "Pull chest toward bar, keep ribs controlled, and lower to full stretch.",
    },
    {
        "name": "Lat Pulldown",
        "category": "strength",
        "muscle_group": "back",
        "description": "Machine vertical pull for lats.",
        "instructions": "Pull bar toward upper chest while keeping shoulders down and torso stable.",
    },
    {
        "name": "Barbell Row",
        "category": "strength",
        "muscle_group": "back",
        "description": "Horizontal pulling movement for upper back.",
        "instructions": "Hinge at hips, brace core, pull bar toward torso, and lower under control.",
    },
    {
        "name": "Seated Cable Row",
        "category": "strength",
        "muscle_group": "back",
        "description": "Cable row for mid-back strength.",
        "instructions": "Sit tall, pull handle to torso, pause briefly, and avoid shrugging.",
    },
    {
        "name": "One-Arm Dumbbell Row",
        "category": "strength",
        "muscle_group": "back",
        "description": "Single-arm row for lats and upper back.",
        "instructions": "Support torso, pull elbow toward hip, and avoid rotating excessively.",
    },
    {
        "name": "Romanian Deadlift",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Hip-hinge movement for hamstrings and glutes.",
        "instructions": "Push hips back, keep spine neutral, and feel a hamstring stretch before standing tall.",
    },
    {
        "name": "Back Squat",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Barbell squat variation for lower-body strength.",
        "instructions": "Brace, descend with knees tracking over toes, and drive up through the full foot.",
    },
    {
        "name": "Front Squat",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Quad-dominant squat with bar held in front rack.",
        "instructions": "Keep elbows high, torso upright, and stand up through midfoot.",
    },
    {
        "name": "Leg Press",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Machine lower-body press.",
        "instructions": "Lower sled to a comfortable depth and press without locking knees aggressively.",
    },
    {
        "name": "Walking Lunges",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Dynamic unilateral leg exercise.",
        "instructions": "Step forward, lower under control, and push through the front foot into the next step.",
    },
    {
        "name": "Leg Curl",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Hamstring isolation machine movement.",
        "instructions": "Curl pad smoothly, pause at the top, and lower under control.",
    },
    {
        "name": "Calf Raises",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Calf isolation movement.",
        "instructions": "Rise onto toes, pause briefly, and lower through a full range of motion.",
    },
    {
        "name": "Bicep Curls",
        "category": "strength",
        "muscle_group": "arms",
        "description": "Arm isolation movement for biceps.",
        "instructions": "Keep elbows near sides, curl without swinging, and lower slowly.",
    },
    {
        "name": "Hammer Curls",
        "category": "strength",
        "muscle_group": "arms",
        "description": "Neutral-grip curl for biceps and forearms.",
        "instructions": "Keep palms facing each other and curl with controlled tempo.",
    },
    {
        "name": "Glute Bridge",
        "category": "strength",
        "muscle_group": "legs",
        "description": "Glute-focused hip extension exercise.",
        "instructions": "Drive through heels, squeeze glutes at the top, and keep ribs down.",
    },
    {
        "name": "Side Plank",
        "category": "core",
        "muscle_group": "core",
        "description": "Anti-lateral-flexion core hold.",
        "instructions": "Stack shoulders and hips, keep body straight, and breathe steadily.",
    },
    {
        "name": "Dead Bug",
        "category": "core",
        "muscle_group": "core",
        "description": "Core stability drill performed on the back.",
        "instructions": "Keep lower back gently pressed down while extending opposite arm and leg.",
    },
    {
        "name": "Russian Twists",
        "category": "core",
        "muscle_group": "core",
        "description": "Rotational core exercise.",
        "instructions": "Rotate torso side to side with control and keep chest lifted.",
    },
    {
        "name": "Bicycle Crunches",
        "category": "core",
        "muscle_group": "core",
        "description": "Core movement combining rotation and hip flexion.",
        "instructions": "Move slowly, rotate shoulder toward opposite knee, and keep neck relaxed.",
    },
    {
        "name": "Hanging Knee Raises",
        "category": "core",
        "muscle_group": "core",
        "description": "Hanging core exercise for lower abs and hip flexors.",
        "instructions": "Hang tall, raise knees under control, and avoid swinging.",
    },
    {
        "name": "Cable Woodchop",
        "category": "core",
        "muscle_group": "core",
        "description": "Cable rotational core movement.",
        "instructions": "Rotate through torso with stable hips and controlled cable path.",
    },
    {
        "name": "Burpees",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Full-body conditioning movement.",
        "instructions": "Move from standing to plank and back with soft landings and controlled pace.",
    },
    {
        "name": "Kettlebell Swing",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Powerful hip-hinge conditioning movement.",
        "instructions": "Hinge, snap hips forward, and let the kettlebell float to chest height.",
    },
    {
        "name": "Jump Squats",
        "category": "hiit",
        "muscle_group": "legs",
        "description": "Explosive squat variation for power and conditioning.",
        "instructions": "Squat to a comfortable depth, jump vertically, and land softly before the next rep.",
    },
    {
        "name": "Box Jumps",
        "category": "hiit",
        "muscle_group": "legs",
        "description": "Explosive jump onto a stable box.",
        "instructions": "Jump onto the box with soft knees, stand tall, and step down under control.",
    },
    {
        "name": "Battle Ropes",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "High-intensity rope waves for conditioning.",
        "instructions": "Keep athletic stance and create strong alternating or double-arm waves.",
    },
    {
        "name": "Medicine Ball Slams",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Explosive full-body conditioning drill.",
        "instructions": "Raise ball overhead, slam forcefully, and reset with a neutral spine.",
    },
    {
        "name": "High Knees",
        "category": "hiit",
        "muscle_group": "legs",
        "description": "Fast-paced running-in-place drill.",
        "instructions": "Drive knees upward quickly while keeping torso tall and arms active.",
    },
    {
        "name": "Jumping Jacks",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Simple full-body conditioning movement.",
        "instructions": "Jump feet out and arms overhead, then return to start with a steady rhythm.",
    },
    {
        "name": "Yoga Flow",
        "category": "mobility",
        "muscle_group": "full body",
        "description": "Continuous yoga sequence for mobility and recovery.",
        "instructions": "Move through poses smoothly while matching breath to movement.",
    },
    {
        "name": "Pilates",
        "category": "mobility",
        "muscle_group": "core",
        "description": "Controlled movement session emphasizing core and alignment.",
        "instructions": "Move slowly with precise control and steady breathing.",
    },
    {
        "name": "Dynamic Stretching",
        "category": "mobility",
        "muscle_group": "full body",
        "description": "Active mobility work before training.",
        "instructions": "Use controlled movement through comfortable ranges before a workout.",
    },
    {
        "name": "Foam Rolling",
        "category": "mobility",
        "muscle_group": "full body",
        "description": "Soft tissue recovery work.",
        "instructions": "Roll slowly over tight areas and pause briefly on tender spots.",
    },
    {
        "name": "Hip Mobility",
        "category": "mobility",
        "muscle_group": "legs",
        "description": "Mobility sequence focused on hips.",
        "instructions": "Move through controlled hip circles, lunges, and stretches without forcing range.",
    },
    {
        "name": "Shoulder Mobility",
        "category": "mobility",
        "muscle_group": "shoulders",
        "description": "Mobility sequence focused on shoulders and upper back.",
        "instructions": "Use slow controlled shoulder circles, wall slides, and gentle stretches.",
    },
    {
        "name": "Tai Chi",
        "category": "mobility",
        "muscle_group": "full body",
        "description": "Low-impact flowing movement practice.",
        "instructions": "Move slowly with relaxed posture and controlled breathing.",
    },
    {
        "name": "Basketball",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Sport activity with running, jumping, and agility.",
        "instructions": "Track active play time and intensity based on game pace.",
    },
    {
        "name": "Soccer",
        "category": "cardio",
        "muscle_group": "legs",
        "description": "Field sport with intermittent running and sprinting.",
        "instructions": "Log active match or practice time and choose intensity based on pace.",
    },
    {
        "name": "Tennis",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Racket sport with agility and repeated short bursts.",
        "instructions": "Track active court time and adjust intensity for singles or doubles.",
    },
    {
        "name": "Pickleball",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Racket sport with lateral movement and coordination.",
        "instructions": "Log active play time and choose intensity based on match pace.",
    },
    {
        "name": "Badminton",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Court sport with quick footwork and overhead shots.",
        "instructions": "Track active play time and use higher intensity for competitive rallies.",
    },
    {
        "name": "Boxing",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Striking workout for conditioning and coordination.",
        "instructions": "Log rounds of bag work, mitts, or shadowboxing with controlled technique.",
    },
    {
        "name": "Kickboxing",
        "category": "hiit",
        "muscle_group": "full body",
        "description": "Striking workout using punches and kicks.",
        "instructions": "Track round duration and maintain controlled form through combinations.",
    },
    {
        "name": "Dancing",
        "category": "cardio",
        "muscle_group": "full body",
        "description": "Rhythmic full-body cardio activity.",
        "instructions": "Log active dance time and choose intensity based on pace.",
    },
]


def seed_library(apps, schema_editor):
    ExerciseLibrary = apps.get_model("workouts", "ExerciseLibrary")
    for item in EXERCISE_LIBRARY_SEEDS:
        obj, created = ExerciseLibrary.objects.get_or_create(name=item["name"], defaults=item)
        if created:
            continue

        changed = []
        for field in ("category", "muscle_group", "description", "instructions"):
            if not getattr(obj, field):
                setattr(obj, field, item[field])
                changed.append(field)
        if changed:
            obj.save(update_fields=changed)


class Migration(migrations.Migration):
    dependencies = [
        ("workouts", "0006_seed_exercise_library"),
    ]

    operations = [
        migrations.RunPython(seed_library, migrations.RunPython.noop),
    ]
