# Generated by Django 4.2 on 2026-02-11 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("brand", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
                ("unit", models.CharField(default="serving", max_length=30)),
                (
                    "calories",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "protein_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "carbs_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fat_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fiber_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sugar_g",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "sodium_mg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("micronutrients", models.JSONField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("usda", "USDA API"),
                            ("image", "Image Recognition"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FoodPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="food_photos/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("recognized_name", models.CharField(blank=True, max_length=150)),
                ("recognized_payload", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="WaterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_ml", models.PositiveIntegerField(default=0)),
                (
                    "consumed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
