# Generated by Django 4.2 on 2026-02-11 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("calories", "Calories"),
                            ("net_calories", "Net Calories"),
                            ("protein", "Protein"),
                            ("carbs", "Carbs"),
                            ("fat", "Fat"),
                            ("water", "Water"),
                            ("workout_minutes", "Workout Minutes"),
                            ("workouts_per_week", "Workouts Per Week"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("unit", models.CharField(default="", max_length=30)),
                (
                    "start_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_push", models.BooleanField(default=True)),
                ("last_notified_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
